Q1. Create a 1D array containing numbers from 1 to 10.  Print:-
 ● Array ● Shape ● Data type ● Sum of elements ● Mean of elements ● Maximum and Minimum values

In [ ]:
import numpy as np

# Create a 1D array from 1 to 10
arr = np.arange(1, 11)

# Print Array
print(f"Array: {arr}")

# Print Shape
print(f"Shape: {arr.shape}")

# Print Data type
print(f"Data type: {arr.dtype}")

# Print Sum of elements
print(f"Sum of elements: {np.sum(arr)}")

# Print Mean of elements
print(f"Mean of elements: {np.mean(arr)}")

# Print Maximum and Minimum values
print(f"Maximum value: {np.max(arr)}")
print(f"Minimum value: {np.min(arr)}")

Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape: (10,)
Data type: int64
Sum of elements: 55
Mean of elements: 5.5
Maximum value: 10
Minimum value: 1


Q2. Create two 3 × 3 matrices.  
A = [[1 2 3] [4 5 6] [7 8 9]]
B = [[9 8 7] [6 5 4] [3 2 1]]
Perform :- 1. Matrix Addition 2. Matrix Subtraction 3. Element-wise Multiplication 4. Matrix Multiplication

In [ ]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# 1. Matrix Addition
matrix_addition = A + B
print("\n1. Matrix Addition (A + B):")
print(matrix_addition)

# 2. Matrix Subtraction
matrix_subtraction = A - B
print("\n2. Matrix Subtraction (A - B):")
print(matrix_subtraction)

# 3. Element-wise Multiplication
element_wise_multiplication = A * B
print("\n3. Element-wise Multiplication (A * B):")
print(element_wise_multiplication)

# 4. Matrix Multiplication
matrix_multiplication = np.dot(A, B) # or A @ B
print("\n4. Matrix Multiplication (A @ B):")
print(matrix_multiplication)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

1. Matrix Addition (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

2. Matrix Subtraction (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

3. Element-wise Multiplication (A * B):
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

4. Matrix Multiplication (A @ B):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Q3. Consider the marks of 5 students in 4 subjects.  [[85,90,88,92], [70,65,72,68], [95,91,93,96], [60,75,70,80], [88,84,86,90]]
Find :- 1. Average marks of each student 2. Average marks of each subject 3. Highest and lowest marks 4. Student having the highest total marks

In [ ]:
import numpy as np

# Marks of 5 students in 4 subjects
marks = np.array([
    [85, 90, 88, 92],
    [70, 65, 72, 68],
    [95, 91, 93, 96],
    [60, 75, 70, 80],
    [88, 84, 86, 90]
])

print("Student Marks:")
print(marks)

# 1. Average marks of each student (mean across rows)
student_avg_marks = np.mean(marks, axis=1)
print("\n1. Average marks of each student:")
for i, avg in enumerate(student_avg_marks):
    print(f"Student {i+1}: {avg:.2f}")

# 2. Average marks of each subject (mean across columns)
subject_avg_marks = np.mean(marks, axis=0)
print("\n2. Average marks of each subject:")
for i, avg in enumerate(subject_avg_marks):
    print(f"Subject {i+1}: {avg:.2f}")

# 3. Highest and lowest marks in the entire dataset
highest_mark = np.max(marks)
lowest_mark = np.min(marks)
print(f"\n3. Highest mark: {highest_mark}")
print(f"Lowest mark: {lowest_mark}")

# 4. Student having the highest total marks
total_marks_per_student = np.sum(marks, axis=1)
highest_total_marks_student_index = np.argmax(total_marks_per_student)
print(f"\n4. Student with the highest total marks (Student {highest_total_marks_student_index + 1}): {total_marks_per_student[highest_total_marks_student_index]}")

Student Marks:
[[85 90 88 92]
 [70 65 72 68]
 [95 91 93 96]
 [60 75 70 80]
 [88 84 86 90]]

1. Average marks of each student:
Student 1: 88.75
Student 2: 68.75
Student 3: 93.75
Student 4: 71.25
Student 5: 87.00

2. Average marks of each subject:
Subject 1: 79.60
Subject 2: 81.00
Subject 3: 81.80
Subject 4: 85.20

3. Highest mark: 96
Lowest mark: 60

4. Student with the highest total marks (Student 3): 375


Q4. A grayscale image is represented by the following matrix. [[100,120,130], [150,180,200], [ 50, 80,100]] Perform :- 1. Normalize pixel values (divide by 255) 2. Increase brightness by 30 3. Clip values above 255 4. Calculate average pixel intensity

In [ ]:
import numpy as np

# Grayscale image represented by a matrix
image_matrix = np.array([
    [100, 120, 130],
    [150, 180, 200],
    [ 50,  80, 100]
])

print("Original Image Matrix:")
print(image_matrix)

# 1. Normalize pixel values (divide by 255)
normalized_image = image_matrix / 255.0
print("\n1. Normalized Image Matrix (divided by 255):")
print(normalized_image)

# 2. Increase brightness by 30
brightness_increased_image = image_matrix + 30
print("\n2. Image Matrix with Brightness Increased by 30:")
print(brightness_increased_image)

# 3. Clip values above 255 (applies to the brightness increased image)
clipped_image = np.clip(brightness_increased_image, 0, 255)
print("\n3. Image Matrix with values clipped above 255:")
print(clipped_image)

# 4. Calculate average pixel intensity (of the original image)
average_intensity = np.mean(image_matrix)
print(f"\n4. Average pixel intensity of the original image: {average_intensity:.2f}")

Original Image Matrix:
[[100 120 130]
 [150 180 200]
 [ 50  80 100]]

1. Normalized Image Matrix (divided by 255):
[[0.39215686 0.47058824 0.50980392]
 [0.58823529 0.70588235 0.78431373]
 [0.19607843 0.31372549 0.39215686]]

2. Image Matrix with Brightness Increased by 30:
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]

3. Image Matrix with values clipped above 255:
[[130 150 160]
 [180 210 230]
 [ 80 110 130]]

4. Average pixel intensity of the original image: 123.33


Q5. A company records the monthly sales of 4 products over 6 months. . [[120,130,140,150,160,170], [100,110,120,130,140,150], [150,145,160,170,180,190], [ 90,100,110,120,130,140]] Perform the following :- 1. Total sales of each product 2. Average monthly sales of each product 3. Best-selling product 4. Month with the highest overall sales 5. Standard deviation of sales for each product

In [ ]:
import numpy as np

# Monthly sales data for 4 products over 6 months
sales_data = np.array([
    [120, 130, 140, 150, 160, 170],
    [100, 110, 120, 130, 140, 150],
    [150, 145, 160, 170, 180, 190],
    [ 90, 100, 110, 120, 130, 140]
])

print("Monthly Sales Data:")
print(sales_data)

# 1. Total sales of each product (sum across columns for each row)
total_sales_per_product = np.sum(sales_data, axis=1)
print("\n1. Total sales of each product:")
for i, total_sales in enumerate(total_sales_per_product):
    print(f"Product {i+1}: {total_sales}")

# 2. Average monthly sales of each product (mean across columns for each row)
average_monthly_sales_per_product = np.mean(sales_data, axis=1)
print("\n2. Average monthly sales of each product:")
for i, avg_sales in enumerate(average_monthly_sales_per_product):
    print(f"Product {i+1}: {avg_sales:.2f}")

# 3. Best-selling product (product with highest total sales)
best_selling_product_index = np.argmax(total_sales_per_product)
print(f"\n3. Best-selling product: Product {best_selling_product_index + 1} with total sales of {total_sales_per_product[best_selling_product_index]}")

# 4. Month with the highest overall sales (sum across rows for each column)
total_sales_per_month = np.sum(sales_data, axis=0)
month_with_highest_sales_index = np.argmax(total_sales_per_month)
print(f"\n4. Month with the highest overall sales: Month {month_with_highest_sales_index + 1} with total sales of {total_sales_per_month[month_with_highest_sales_index]}")

# 5. Standard deviation of sales for each product
std_dev_sales_per_product = np.std(sales_data, axis=1)
print("\n5. Standard deviation of sales for each product:")
for i, std_dev in enumerate(std_dev_sales_per_product):
    print(f"Product {i+1}: {std_dev:.2f}")

Monthly Sales Data:
[[120 130 140 150 160 170]
 [100 110 120 130 140 150]
 [150 145 160 170 180 190]
 [ 90 100 110 120 130 140]]

1. Total sales of each product:
Product 1: 870
Product 2: 750
Product 3: 995
Product 4: 690

2. Average monthly sales of each product:
Product 1: 145.00
Product 2: 125.00
Product 3: 165.83
Product 4: 115.00

3. Best-selling product: Product 3 with total sales of 995

4. Month with the highest overall sales: Month 6 with total sales of 650

5. Standard deviation of sales for each product:
Product 1: 17.08
Product 2: 17.08
Product 3: 15.92
Product 4: 17.08
